# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ch6fseRWKqzK8cAmQW6SUriAyuytvQiW
"""

for i in range(1,6):
  for j in range(1,5):
    print("*",end=" ")
  print("")

for i in range(1,6):
  for j in range(1,5):
    print(j,end=" ")
  print("")

for i in range(1,4):
  for j in range(1,5):
    print(i,end=" ")
  print("")

for i in range(3,0,-1):
  for j in range(1,5):
    print(i,end=" ")
  print("")

for i in range(1,4):
  x = 2
  for j in range(1,4):
    print(x,end=" ")
    x+=1
  print("")

n = 9
for i in range(1,4):
  for j in range(1,4):
    print(n,end=" ")
    n-=1
  print("")

n = 1
for i in range(1,4):
  for j in range(1,4):
    print(n,end=" ")
    n+=1
  print("")

for i in range(1,6):
  for j in range(1,i+1):
    print("*",end=" ")
  print("")

for i in range(1,6):
  for j in range(1,i+1):
    print("5",end=" ")
  print("")

for i in range(1,4):
  for j in range(1,4):
    if(j==1 or i==3 or i==j):
      print(j,end=" ")
  print("")

n = 7
for i in range(1,4):
  for j in range(1,4):
    if(j==1 or i==3 or i==j):
      print(n,end=" ")
      n-=1
  print("")



for i in range(1,4):
  for j in range(i,5):
    print("-",end=" ")

  for j in range(1,i+1):
    print("*",end=" ")
  print("")

for i in range(1,5):
  for j in range(1,i):
    print("-",end=" ")

  for j in range(1,6-i):
    print("*",end=" ")
  print("")

n = 6
for i in range(1,n+1):
  for j in range(1,i+1):
    if(j==1 or i==6 or i==j):
      print("*",end=" ")
    else:
      print("-",end=" ")
  print("")

for i in range(6,0,-1):
  for j in range(1,i+1):
    if(j==1 or i==6 or i==j):
      print("*",end=" ")
    else:
      print("-",end=" ")
  print("")

n = 5
for i in range(5,0,-1):
  for j in range(1,i+1):
    if(j==5 or i==1 or i==j):
      print("*",end=" ")
    else:
      print("-",end=" ")
  for j in range(1,6-i):
    if(j==5 or i==1 or i==j):
      print("*",end=" ")
    else:
      print("*",end=" ")
  print("")